#pragma once
#include <iostream>
#include <string>
#include <map>

static std::map<int, std::string> types_values = {

    { 1 , "alert" },
    { 2 , "midi" },
    { 3 , "osc" },
    { 4 , "artnet" },
    { 5 , "rgb-color" },
    { 6 , "hex-color" },
    { 7 , "chat-command" },
    { 8 , "twitch-points" },
    { 9 , "twitch-extension" },
    { 10 , "trovo-spells" },
    { 11 , "studio-scene" },
    { 12 , "studio-animation" },
    { 13 , "studio-theme" },
    { 14 , "chatbot-messsage" },
    { 15 , "tts" },


    { 16 , "twitch-follower" },
    { 17 , "twitch-subscriber" },
    { 18 , "twitch-bits" },
    { 19 , "twitch-host" },
    { 20 , "twitch-raid" },
    { 21 , "youtube-subscriber" },
    { 22 , "youtube-superchat" },
    { 23 , "youtube-supersticker" },
    { 24 , "youtube-member" },
    { 25 , "facebook-follower" },
    { 26 , "facebook-reaction" },
    { 27 , "facebook-star" },
    { 28 , "facebook-support" },
    { 29 , "facebook-share" },
    { 30 , "facebook-fan" },
    { 31 , "trovo-follower" },
    { 32 , "trovo-subscriber" },
    { 33 , "streamlabs-donation" },
    { 34 , "streamlabs-merch" },
    { 35 , "streamlabs-redemption" },
    { 36 , "streamlabs-primegift" },
    { 37 , "streamelements-donation" },
    { 38 , "obs-switchProfile" },
    { 39 , "obs-switchScene" },
    { 40 , "obs-switch-transition" },
    { 41 , "obs-streamStarting" },
    { 42 , "obs-streamStopping" },
    { 43 , "slobs-switchScene" },
    { 44 , "treatstream-treat" },
    { 45 , "pulse-heartrate" },
    { 46 , "pulse-calories" },

    { 47 , "chat" },
    { 48 , "chat/twitch" },
    { 49 , "chat/facebook" },
    { 50 , "chat/youtube" },
    { 51 , "chat/glimesh" },
    { 68 , "alerts/twitch" },
    { 69 , "alerts/twitch/followers" },
    { 70 , "alerts/twitch/subscribers" },
    { 71 , "alerts/twitch/bits" },
    { 72 , "alerts/twitch/hosts" },
    { 73 , "alerts/twitch/raids" },
    { 74 , "alerts/youtube" },
    { 75 , "alerts/youtube/subscribers" },
    { 76 , "alerts/youtube/members" },
    { 77 , "alerts/youtube/superchats" },
    { 78 , "alerts/youtube/superstickers" },
    { 79 , "alerts/facebook" },
    { 80 , "alerts/facebook/followers" },
    { 81 , "alerts/facebook/reactions" },
    { 82 , "alerts/facebook/stars" },
    { 83 , "alerts/facebook/supports" },
    { 84 , "alerts/facebook/shares" },
    { 85 , "alerts/facebook/fans" },
    { 86 , "alerts/glimesh" },
    { 87 , "alerts/glimesh/followers" },
    { 88 , "alerts/glimesh/subscribers" },
    { 89 , "alerts/streamlabs" },
    { 90 , "alerts/streamlabs/donations" },
    { 91 , "alerts/streamlabs/charity" },
    { 92 , "alerts/streamlabs/merch" },
    { 93 , "alerts/streamlabs/redemptions" },
    { 94 , "alerts/streamlabs/primegifts" },
    { 95 , "alerts/streamelements" },
    { 96 , "alerts/streamelements/donations" },
    { 97 , "alerts/streamelements/merch" },
    { 98 , "alerts/streamelements/redemptions" },
    { 99 , "alerts/extralife/donations" },
    { 100 , "alerts/donordrive/donations" },
    { 101 , "alerts/paypal/paymentcomplete" },
    { 102 , "alerts/tipeeestream/paymentdenied" },
    { 103 , "alerts/tipeestream/donations" },
    { 104 , "alerts/tiltify/campaigndonations" },
    { 105 , "alerts/patreon/campaignpledges" },
    { 106 , "alerts/treatstream/treats" },
    { 107 , "alerts/obs" },
    { 108 , "alerts/slobs" },
    { 109 , "alerts/pulse/rate" },
    { 110 , "alerts/pulse/calories" },


    { 111, "twitch" },
    { 112, "youtube" },
    { 113, "facebook" },
    { 114, "trovo" },
    { 115, "glimesh" },


    { 116, "hue" },
    { 117 , "nanoleaf" },
    { 118 , "nanoleaf2" },
    { 119 , "lifx" },
    { 120 , "tplink" },
    { 121 , "yeelight" },
    { 122 , "cololight" },
    { 123 , "tuya" },
    { 124 , "smartlife" },
    { 125 , "wyze" },
    { 126 , "wiz" },
    { 127 , "homeassistant" },
    { 128 , "govee" },
    { 129 , "wled" },
    { 130 , "magichome" },
    { 131 , "logitech" },
    { 132 , "razer" },
    { 133 , "corsair" },
    { 134 , "steelseries" },
    { 135 , "overlay" },
    { 136 , "elgato" },


    { 137 , "lumia" },
    { 138 , "twitch" },
    { 139 , "youtube" },
    { 140 , "facebook" },
    { 141 , "glimesh" },
    { 142 , "trovo" },
    { 143 , "streamlabs" },
    { 144 , "streamelements" },
    { 145 , "extralife" },
    { 146 , "donordrive" },
    { 147 , "tiltify" },
    { 148 , "patreon" },
    { 149 , "tipeeestream" },
    { 150 , "treatstream" },
    { 151 , "discord" },
    { 152 , "obs" },
    { 153 , "slobs" },
    { 154 , "pulsoid" },
    { 155 , "paypal" }


};

static std::map<std::string, int > types_values_str = {
    { "alert", 1},
    { "midi" , 2 },
    { "osc" , 3 },
    { "artnet" , 4 },
    { "rgb-color" , 5 },
    { "hex-color" , 6 },
    { "chat-command" , 7 },
    { "twitch-points" , 8 },
    { "twitch-extension" , 9 },
    { "trovo-spells" , 10 },
    { "studio-scene" , 11 },
    { "studio-animation" , 12 },
    { "studio-theme" , 13 },
    { "chatbot-messsage" , 14 },
    { "tts" , 15 },
    { "twitch-follower" , 16 },
    { "twitch-subscriber" , 17 },
    { "twitch-bits" , 18 },
    { "twitch-host" , 19 },
    { "twitch-raid" , 20 },
    { "youtube-subscriber" , 21 },
    { "youtube-superchat" , 22 },
    { "youtube-supersticker" , 23 },
    { "youtube-member" , 24 },
    { "facebook-follower" , 25 },
    { "facebook-reaction" , 26 },
    { "facebook-star" , 27 },
    { "facebook-support" , 28 },
    { "facebook-share" , 29 },
    { "facebook-fan" , 30 },
    { "trovo-follower" , 31 },
    { "trovo-subscriber" , 32 },
    { "streamlabs-donation" , 33 },
    { "streamlabs-merch" , 34 },
    { "streamlabs-redemption" , 35 },
    { "streamlabs-primegift" , 36 },
    { "streamelements-donation" , 37 },
    { "obs-switchProfile" , 38 },
    { "obs-switchScene" , 39 },
    { "obs-switch-transition" , 40 },
    { "obs-streamStarting" , 41 },
    { "obs-streamStopping" , 42 },
    { "slobs-switchScene" , 43 },
    { "treatstream-treat" , 44 },
    { "pulse-heartrate" , 45 },
    { "pulse-calories" , 46 },
    { "chat" , 47 },
    { "chat/twitch" , 48 },
    { "chat/facebook" , 49 },
    { "chat/youtube" , 50 },
    { "chat/glimesh" , 51 },
    { "alerts/twitch" , 68 },
    { "alerts/twitch/followers" , 69 },
    { "alerts/twitch/subscribers" , 70 },
    { "alerts/twitch/bits" , 71 },
    { "alerts/twitch/hosts" , 72 },
    { "alerts/twitch/raids" , 73 },
    { "alerts/youtube" , 74 },
    { "alerts/youtube/subscribers" , 75 },
    { "alerts/youtube/members" , 76 },
    { "alerts/youtube/superchats" , 77 },
    { "alerts/youtube/superstickers" , 78 },
    { "alerts/facebook" , 79 },
    { "alerts/facebook/followers" , 80 },
    { "alerts/facebook/reactions" , 81 },
    { "alerts/facebook/stars" , 82 },
    { "alerts/facebook/supports" , 83 },
    { "alerts/facebook/shares" , 84 },
    { "alerts/facebook/fans" , 85 },
    { "alerts/glimesh" , 86 },
    { "alerts/glimesh/followers" , 87 },
    { "alerts/glimesh/subscribers" , 88 },
    { "alerts/streamlabs" , 89 },
    { "alerts/streamlabs/donations" , 90 },
    { "alerts/streamlabs/charity" , 91 },
    { "alerts/streamlabs/merch" , 92 },
    { "alerts/streamlabs/redemptions" , 93 },
    { "alerts/streamlabs/primegifts" , 94 },
    { "alerts/streamelements" , 95 },
    { "alerts/streamelements/donations" , 96 },
    { "alerts/streamelements/merch" , 97 },
    { "alerts/streamelements/redemptions" , 98 },
    { "alerts/extralife/donations" , 99 },
    { "alerts/donordrive/donations" , 100 },
    { "alerts/paypal/paymentcomplete" , 101 },
    { "alerts/tipeeestream/paymentdenied" , 102 },
    { "alerts/tipeestream/donations" , 103 },
    { "alerts/tiltify/campaigndonations" , 104 },
    { "alerts/patreon/campaignpledges" , 105 },
    { "alerts/treatstream/treats" , 106 },
    { "alerts/obs" , 107 },
    { "alerts/slobs" , 108 },
    { "alerts/pulse/rate" , 109 },
    { "alerts/pulse/calories" , 110 },
    { "twitch" , 111 },
    { "youtube" , 112 },
    { "facebook" , 113 },
    { "trovo" , 114 },
    { "glimesh" , 115 },
    { "hue" , 116 },
    { "nanoleaf" , 117 },
    { "nanoleaf2" , 118 },
    { "lifx" , 119 },
    { "tplink" , 120 },
    { "yeelight" , 121 },
    { "cololight" , 122 },
    { "tuya" , 123 },
    { "smartlife" , 124 },
    { "wyze" , 125 },
    { "wiz" , 126 },
    { "homeassistant" , 127 },
    { "govee" , 128 },
    { "wled" , 129 },
    { "magichome" , 130 },
    { "logitech" , 131 },
    { "razer" , 132 },
    { "corsair" , 133 },
    { "steelseries" , 134 },
    { "overlay" , 135 },
    { "elgato" , 136 },
    { "lumia" , 137 },
    { "twitch" , 138 },
    { "youtube" , 139 },
    { "facebook" , 140 },
    { "glimesh" , 141 },
    { "trovo" , 142 },
    { "streamlabs" , 143 },
    { "streamelements" , 144 },
    { "extralife" , 145 },
    { "donordrive" , 146 },
    { "tiltify" , 147 },
    { "patreon" , 148 },
    { "tipeeestream" , 149 },
    { "treatstream" , 150 },
    { "discord" , 151 },
    { "obs" , 152 },
    { "slobs" , 153 },
    { "pulsoid" , 154 },
    { "paypal" , 155 }

};


